import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import type { VisibilityFilter } from '../types.js';
import type { KnowledgeBlocks, SyncKnowledgeSource } from './types.js';

const IVN_START_MARKER = '<!-- IVN:START -->';
const IVN_END_MARKER = '<!-- IVN:END -->';

export function gatherKnowledge(
  store: SyncKnowledgeSource,
  visibility: VisibilityFilter = 'shared',
): KnowledgeBlocks {
  return {
    decisions: store.listAll({ type: 'decision', visibility }),
    patterns: store.listAll({ type: 'pattern', visibility }),
    gotchas: store.listAll({ type: 'gotcha', visibility }),
    debugs: store.listAll({ type: 'debug', visibility }),
    dependencies: store.listAll({ type: 'dependency', visibility }),
    todos: store.listAll({ type: 'todo', visibility }),
    contexts: store.listAll({ type: 'context', visibility }),
  };
}

export function hasContent(blocks: KnowledgeBlocks): boolean {
  return (
    blocks.decisions.length + blocks.patterns.length + blocks.gotchas.length +
    blocks.debugs.length + blocks.dependencies.length + blocks.todos.length +
    blocks.contexts.length
  ) > 0;
}

export function buildCoreMarkdown(blocks: KnowledgeBlocks): string {
  let md = '';

  if (blocks.contexts.length > 0) {
    md += `## Project Context\n\n`;
    for (const c of blocks.contexts) md += `- ${c.content}\n`;
    md += '\n';
  }

  if (blocks.decisions.length > 0) {
    md += `## Architectural Decisions\n\n`;
    md += `These decisions have been made. Follow them consistently:\n\n`;
    for (const d of blocks.decisions) md += `- ${d.content}\n`;
    md += '\n';
  }

  if (blocks.patterns.length > 0) {
    md += `## Coding Patterns & Conventions\n\n`;
    md += `Always follow these established patterns:\n\n`;
    for (const p of blocks.patterns) md += `- ${p.content}\n`;
    md += '\n';
  }

  if (blocks.gotchas.length > 0) {
    md += `## Known Gotchas & Pitfalls\n\n`;
    md += `Be aware of these issues. Warn the developer if relevant:\n\n`;
    for (const g of blocks.gotchas) md += `- \u26A0 ${g.content}\n`;
    md += '\n';
  }

  if (blocks.debugs.length > 0) {
    md += `## Past Bugs & Fixes\n\n`;
    md += `These bugs have been fixed before. Avoid reintroducing them:\n\n`;
    for (const d of blocks.debugs) md += `- ${d.content}\n`;
    md += '\n';
  }

  if (blocks.dependencies.length > 0) {
    md += `## Dependencies & Constraints\n\n`;
    for (const d of blocks.dependencies) md += `- ${d.content}\n`;
    md += '\n';
  }

  if (blocks.todos.length > 0) {
    md += `## Active Work & TODOs\n\n`;
    for (const t of blocks.todos) md += `- [ ] ${t.content}\n`;
    md += '\n';
  }

  md += `## Capture New Knowledge\n\n`;
  md += `When you discover something important while working — a decision, gotcha, bug fix, or pattern — persist it so future sessions already know:\n\n`;
  md += '```\n';
  md += 'ivn remember "what you learned and WHY" --type gotcha --tags relevant,tags\n';
  md += '```\n\n';
  md += 'Types: `decision` · `pattern` · `gotcha` · `debug` · `dependency` · `todo`\n\n';

  return md;
}

export function upsertManagedMarkdown(path: string, block: string): void {
  let existing = '';
  if (existsSync(path)) {
    existing = stripManagedMarkdown(readFileSync(path, 'utf-8')).trimEnd();
  }

  const prefix = existing ? `${existing}\n\n` : '';
  writeFileSync(path, prefix + block);
}

export function buildManagedMarkdownBlock(title: string, body: string): string {
  return `${IVN_START_MARKER}
<!-- Auto-generated by ivn sync-rules. Do not edit this section. -->

${title}

${body}${IVN_END_MARKER}
`;
}

function stripManagedMarkdown(markdown: string): string {
  const start = markdown.indexOf(IVN_START_MARKER);
  const end = markdown.indexOf(IVN_END_MARKER);
  if (start === -1 || end === -1) return markdown;
  return markdown.slice(0, start) + markdown.slice(end + IVN_END_MARKER.length);
}
