import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildCoreMarkdown } from './core.js';
import type { RuleAdapter, RuleSyncTarget } from './types.js';

function createSimpleMarkdownAdapter(
  id: RuleSyncTarget,
  label: string,
  relativePath: string,
  title: string,
  intro: string[],
  detectPath?: string,
): RuleAdapter {
  return {
    id,
    label,
    detect(root) {
      return detectPath ? existsSync(join(root, detectPath)) : existsSync(join(root, relativePath));
    },
    sync(root, blocks) {
      const path = join(root, relativePath);
      const content = [
        title,
        '',
        ...intro,
        '',
        buildCoreMarkdown(blocks),
      ].join('\n');
      writeFileSync(path, content);
      return { target: label, path };
    },
  };
}

export const simpleMarkdownAdapters: RuleAdapter[] = [
  createSimpleMarkdownAdapter(
    'windsurf',
    'Windsurf',
    '.windsurfrules',
    '# Project Knowledge (via ivn)',
    ['> Auto-generated by `ivn sync-rules`. Do not edit manually.'],
  ),
  createSimpleMarkdownAdapter(
    'cline',
    'Cline',
    '.clinerules',
    '# Project Knowledge (via ivn)',
    ['> Auto-generated by `ivn sync-rules`. Do not edit manually.'],
  ),
  createSimpleMarkdownAdapter(
    'generic',
    'Generic (KNOWLEDGE.md)',
    'KNOWLEDGE.md',
    '# Project Knowledge',
    [
      '> Auto-generated by [ivn](https://github.com/boona13/ivn). Regenerate with: `ivn sync-rules`',
      '>',
      '> Point any AI agent to this file to load project context.',
    ],
  ),
];
