import { normalizeFileRef } from './knowledge-heuristics.js';
import {
  isWarningType,
  pluralTypeLabel,
  scoreCandidate,
  scoreFileMatches,
  scoreFreshness,
  warningPriority,
} from './knowledge-ranking.js';
import type {
  Knowledge,
  KnowledgeType,
  ReviewStatusFilter,
  SearchResult,
  VisibilityFilter,
} from './types.js';

export function normalizeScopedFilePaths(filePaths: string[], root: string): string[] {
  return [...new Set(
    filePaths
      .map((filePath) => normalizeFileRef(filePath, root))
      .filter(Boolean),
  )];
}

export function buildFocusedKnowledge(options: {
  entries: Knowledge[];
  filePaths: string[];
  root: string;
  limit: number;
  visibility: VisibilityFilter;
  reviewStatus: ReviewStatusFilter;
  getRelated: (id: string) => Array<{ knowledge: Knowledge }>;
  matchesVisibility: (entry: Knowledge | null, visibility: VisibilityFilter) => boolean;
  matchesReviewStatus: (
    entry: Knowledge | null,
    reviewStatus: ReviewStatusFilter | 'all_active_or_pending',
  ) => boolean;
}): SearchResult[] {
  const {
    entries,
    filePaths,
    root,
    limit,
    visibility,
    reviewStatus,
    getRelated,
    matchesVisibility,
    matchesReviewStatus,
  } = options;
  const normalizedFilePaths = normalizeScopedFilePaths(filePaths, root);
  if (normalizedFilePaths.length === 0) return [];

  const scored = new Map<string, { entry: Knowledge; score: number }>();
  for (const entry of entries) {
    const directScore = scoreFileMatches(entry, normalizedFilePaths, root);
    if (directScore <= 0) continue;
    scoreCandidate(
      scored,
      entry,
      directScore + Math.round(entry.confidence * 20) + scoreFreshness(entry),
    );
  }

  const directMatches = [...scored.values()];
  for (const { entry, score } of directMatches) {
    for (const related of getRelated(entry.id)) {
      if (
        !matchesVisibility(related.knowledge, visibility) ||
        !matchesReviewStatus(related.knowledge, reviewStatus)
      ) {
        continue;
      }
      const relatedScore = Math.max(18, Math.floor(score * 0.35)) + scoreFreshness(related.knowledge);
      scoreCandidate(scored, related.knowledge, relatedScore);
    }
  }

  return [...scored.values()]
    .sort((a, b) => b.score - a.score || b.entry.created_at.localeCompare(a.entry.created_at))
    .slice(0, limit)
    .map(({ entry, score }) => ({
      ...entry,
      rank: -score,
    }));
}

export function buildWarningKnowledge(focused: SearchResult[], limit: number): SearchResult[] {
  return focused
    .filter((entry) => isWarningType(entry.type))
    .map((entry, index) => ({
      entry,
      score:
        warningPriority(entry.type) * 1000 +
        scoreFreshness(entry) +
        Math.max(0, 120 - index * 4),
    }))
    .sort((a, b) => b.score - a.score || b.entry.created_at.localeCompare(a.entry.created_at))
    .slice(0, limit)
    .map(({ entry, score }) => ({
      ...entry,
      rank: -score,
    }));
}

export function renderProjectContext(options: {
  projectName: string;
  entries: Knowledge[];
  warnings: SearchResult[];
  focusedFilePath?: string;
}): string {
  const { projectName, warnings, focusedFilePath } = options;
  let entries = [...options.entries];

  if (entries.length === 0) return 'No project knowledge stored yet. Run `ivn remember` to add some.';

  let output = `# Project Knowledge — ${projectName}\n`;
  output += `> Generated by ivn · ${entries.length} entries\n\n`;
  if (focusedFilePath) {
    output += `> Focused on \`${focusedFilePath}\`\n\n`;
  }
  if (warnings.length > 0) {
    output += '## Warnings\n\n';
    for (const warning of warnings) {
      output += `- ${warning.content}\n`;
    }
    output += '\n';
    const warningIds = new Set(warnings.map((warning) => warning.id));
    entries = entries.filter((entry) => !warningIds.has(entry.id));
  }

  for (const type of TYPE_ORDER) {
    const items = entries.filter((entry) => entry.type === type);
    if (items.length === 0) continue;

    const label = pluralTypeLabel(type);
    output += `## ${label}\n\n`;
    for (const item of items) {
      output += `- ${item.content}`;
      if (item.tags.length) output += ` _(${item.tags.join(', ')})_`;
      output += '\n';
    }
    output += '\n';
  }

  return output.trimEnd() + '\n';
}

export function renderChangedKnowledgeContext(options: {
  projectName: string;
  filePaths: string[];
  entries: Knowledge[];
  warnings: SearchResult[];
}): string {
  const { projectName, filePaths, warnings } = options;
  const entries = [...options.entries];
  if (filePaths.length === 0) {
    return 'No changed files detected.';
  }
  if (entries.length === 0 && warnings.length === 0) {
    return `# Changed File Context\n> ${filePaths.length} changed file${filePaths.length === 1 ? '' : 's'}\n\nNo related project knowledge found yet.\n`;
  }

  const lines: string[] = [
    `# Changed File Context — ${projectName}`,
    `> ${filePaths.length} changed file${filePaths.length === 1 ? '' : 's'} · ${entries.length} relevant knowledge entr${entries.length === 1 ? 'y' : 'ies'}`,
    '',
    '## Changed Files',
    '',
    ...filePaths.map((filePath) => `- \`${filePath}\``),
    '',
  ];

  if (warnings.length > 0) {
    lines.push('## Warnings');
    lines.push('');
    for (const warning of warnings) {
      lines.push(`- ${warning.content}`);
    }
    lines.push('');
  }

  for (const type of TYPE_ORDER) {
    const items = entries.filter((entry) => entry.type === type);
    if (items.length === 0) continue;

    const label = pluralTypeLabel(type);
    lines.push(`## ${label}`);
    lines.push('');
    for (const item of items) {
      lines.push(`- ${item.content}`);
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}

const TYPE_ORDER: KnowledgeType[] = [
  'context', 'decision', 'pattern', 'gotcha', 'dependency', 'debug', 'todo',
];
